backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

site_url: https://yorspace.org

media_folder: "uploads" # Media files will be stored in the repo under uploads
publish_mode: editorial_workflow

collections:
  - name: "site" # Used in routes, e.g., /admin/collections/blog
    label: "Site" # Used in the UI
    editor:
      preview: false
    files:
      - label: "Banner"
        name: "banner"
        file: "_data/site.json"
        fields: # The fields for each document, usually in front matter
          - label: "Site-wide banner"
            name: "banner"
            widget: "object"
            fields:
              - { label: 'Text', name: 'text', widget: 'string', required: false }
              - { label: 'Button text', name: 'button_text', widget: 'string', required: false }
              - { label: 'Button URL', name: 'button_url', widget: 'string', required: false }
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    summary: "{{title}} – {{day}}.{{month}}.{{year}}"
    preview_path: "_posts/{{slug}}"
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime", timeFormat: false}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "string", required: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - {label: "File", name: "file", widget: "image"}
          - {label: "Caption", name: "caption", widget: "string", required: false}
          - {label: "Show image at top of post?", name: "show_on_post", widget: "boolean", default: true }
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    preview_path: "{{ name | slug }}/index.html"
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "text", required: false}
      - {label: "Content", name: "body", widget: "markdown", required: false}
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
  - name: "faqs" # Used in routes, e.g., /admin/collections/blog
    label: "FAQs" # Used in the UI
    editor:
      preview: false
    folder: "_faqs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Location", name: "location", widget: "select", multiple: true, options: ["home", "live", "invest"]}