backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: "uploads" # Media files will be stored in the repo under uploads

collections:
  - name: "blog" # Used in routes, e.g., /admin/collections/blog
    label: "Blog" # Used in the UI
    folder: "_posts" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Tags", name: "tags", widget: "string"}
      - label: "Image"
        name: "image"
        widget: "object"
        fields:
          - {label: "File", name: "file", widget: "image"}
          - {label: "Caption", name: "caption", widget: "string"}
          - {label: "Show on post?", name: "show_on_post", widget: "boolean" }
  - name: "pages" # Used in routes, e.g., /admin/collections/blog
    label: "Pages" # Used in the UI
    folder: "_pages" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Subtitle", name: "subtitle", widget: "markdown"}
  - name: "faqs" # Used in routes, e.g., /admin/collections/blog
    label: "FAQs" # Used in the UI
    editor:
      preview: false
    folder: "_faqs" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
      - {label: "Location", name: "location", widget: "select", multiple: true, options: ["home", "live", "invest"]}